CREATE TABLE IF NOT EXISTS install_state (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    step_key VARCHAR(190) NOT NULL UNIQUE,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    payload JSON NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
